# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IBxS5f06GJ6MZsnAy5nBWE9hDhG6VA1w
"""

!pip install xgboost shap --quiet

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

from xgboost import XGBClassifier
import shap
import pickle
import warnings

from google.colab import files
uploaded = files.upload()

df = pd.read_csv('Crop_recommendation.csv')
print(df.shape)
df.head()

features = ['N', 'P', 'K', 'temperature', 'humidity', 'ph', 'rainfall']

df_clean = df.copy()

for col in features:
    Q1 = df_clean[col].quantile(0.25)
    Q3 = df_clean[col].quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    df_clean[col] = df_clean[col].clip(lower, upper)

print(f"Rows before: {len(df)} | Rows after: {len(df_clean)}")

le = LabelEncoder()
df_clean['label_encoded'] = le.fit_transform(df_clean['label'])

print("Crop → Number mapping:")
for i, crop in enumerate(le.classes_):
    print(f"  {crop} → {i}")

X = df_clean[features]
y = df_clean['label_encoded']

# Train/test split (stratified)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# Scale features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled  = scaler.transform(X_test)

print(f"✅ Train size: {X_train.shape} | Test size: {X_test.shape}")

xgb_model = XGBClassifier(
    n_estimators=200,
    max_depth=6,
    learning_rate=0.1,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    use_label_encoder=False,
    eval_metric='mlogloss'
)

xgb_model.fit(X_train_scaled, y_train)

# ====================== REALISTIC FEATURE RANGES ======================
FEATURE_RANGES = {
    'N':          (0,  140),
    'P':          (5,  145),
    'K':          (5,  205),
    'temperature': (8,  43),     # Very few crops survive above 40-42°C
    'humidity':   (10, 100),
    'ph':         (3.5, 9.5),
    'rainfall':   (20, 300)
}

def validate_crop_input(user_input: dict):
    """
    Returns: (is_valid: bool, warning_message: str)
    """
    warnings = []

    for feature, value in user_input.items():
        if feature in FEATURE_RANGES:
            min_val, max_val = FEATURE_RANGES[feature]
            if value < min_val or value > max_val:
                warnings.append(f"• {feature} = {value} is outside realistic range ({min_val} – {max_val})")

    # Extra strong warning for extreme temperature
    temp = user_input.get('temperature')
    if temp is not None:
        if temp > 40:
            warnings.append(f"• Temperature = {temp}°C is EXTREMELY HIGH. Most crops will suffer severe heat stress.")
        elif temp > 37:
            warnings.append(f"• Temperature = {temp}°C is very high and risky for many crops.")

    if warnings:
        return False, "\n".join(warnings)
    return True, ""

y_pred = xgb_model.predict(X_test_scaled)
print(f"✅ XGBoost Accuracy: {accuracy_score(y_test, y_pred)*100:.2f}%")
print("\nClassification Report:")
print(classification_report(y_test, y_pred, target_names=le.classes_))

cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(16, 14))
sns.heatmap(cm, annot=True, fmt='d',
            xticklabels=le.classes_,
            yticklabels=le.classes_,
            cmap='Greens')
plt.title('XGBoost Confusion Matrix')
plt.ylabel('Actual')
plt.xlabel('Predicted')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

cv_scores = cross_val_score(xgb_model, X_train_scaled, y_train, cv=5)

print("Cross-Validation Scores:", cv_scores)
print(f"Mean CV Accuracy: {cv_scores.mean()*100:.2f}%")
print(f"Std Dev:          {cv_scores.std()*100:.2f}%")

knn_model = KNeighborsClassifier(
    n_neighbors=5,
    metric='euclidean',
    weights='distance'
)

knn_model.fit(X_train_scaled, y_train)

knn_pred = knn_model.predict(X_test_scaled)
print(f"✅ KNN Accuracy: {accuracy_score(y_test, knn_pred)*100:.2f}%")

explainer = shap.TreeExplainer(xgb_model)
shap_values = explainer.shap_values(X_test_scaled)

# Summary plot
shap.summary_plot(shap_values, X_test, feature_names=features, plot_type="bar")



import json
# Helper function to convert numpy types to native Python types
def convert_to_serializable(obj):
    if isinstance(obj, np.ndarray):
        return obj.tolist()
    elif isinstance(obj, (np.float32, np.float64)):
        return float(obj)
    elif isinstance(obj, (np.int32, np.int64)):
        return int(obj)
    elif isinstance(obj, dict):
        return {k: convert_to_serializable(v) for k, v in obj.items()}
    elif isinstance(obj, (list, tuple)):
        return [convert_to_serializable(i) for i in obj]
    return obj
# ====================== USER PREDICTION BLOCK ======================
user_input = {
    'N': 90,
    'P': 42,
    'K': 43,
    'temperature': 30,      # Test with 50
    'humidity': 82.0,
    'ph': 6.5,
    'rainfall': 202.0
}

# Step 1: Validation (Upper RAG Layer)
is_valid, warning_msg = validate_crop_input(user_input)

print("🔍 Input Validation:")
if not is_valid:
    print("⚠️  UNREALISTIC INPUT DETECTED!")
    print(warning_msg)
    print("\n🌡️  Conclusion: These conditions (especially 50°C temperature) are **not suitable** for any crop in our database.")
    print("   Most crops will face severe heat damage, reduced yield, or complete failure at such high temperatures.\n")

# Step 2: Still run the model but with clear disclaimer
input_df = pd.DataFrame([user_input])
input_scaled = scaler.transform(input_df)

pred_encoded = xgb_model.predict(input_scaled)[0]
pred_crop = le.inverse_transform([pred_encoded])[0]
pred_proba = xgb_model.predict_proba(input_scaled)[0]
confidence = round(float(pred_proba[pred_encoded] * 100), 2)
top3_idx = pred_proba.argsort()[-3:][::-1]
top3_crops = [(le.classes_[i], round(pred_proba[i]*100, 2)) for i in top3_idx]

# SHAP values for predicted class
shap_values = explainer.shap_values(input_scaled)           # shape: (1, 7, n_classes)
shap_for_pred = shap_values[0, :, pred_encoded]             # Correct indexing

feature_importance = {
    feature: round(float(value), 4)
    for feature, value in zip(features, shap_for_pred)
}

# ====================== IMPROVED SIMILAR CASES (Corrected) ======================
print(f"🌾 Model Prediction : {pred_crop.upper()}")
print(f"📊 Model Confidence : {pred_proba[pred_encoded]*100:.2f}%")

if not is_valid:
    print("   ⚠️  Note: This prediction is **unreliable** because input is outside training range.")

print(f"\n🔢 Top 3 Crops:")
for crop, conf in top3_crops:
    print(f"   {crop.capitalize()}: {conf}%")

print(f"\n🧠 Feature Contribution (SHAP) for {pred_crop}:")
for k, v in sorted(feature_importance.items(), key=lambda x: abs(x[1]), reverse=True):
    print(f"   {k:12}: {v:+.4f}")


temp = user_input.get('temperature')
rain = user_input.get('rainfall')

# Filter candidates with reasonably similar climate
candidates = df_clean[
    (df_clean['temperature'].between(temp - 6, temp + 6)) &
    (df_clean['rainfall'].between(rain - 60, rain + 60))
].copy()

if len(candidates) >= 3:
    X_cand_scaled = scaler.transform(candidates[features])
    nn = NearestNeighbors(n_neighbors=min(5, len(candidates)), metric='euclidean')
    nn.fit(X_cand_scaled)
    _, indices = nn.kneighbors(input_scaled)
    similar_df = candidates.iloc[indices[0]]
else:
    _, indices = knn_model.kneighbors(input_scaled, n_neighbors=5)
    similar_df = df_clean.iloc[indices[0]]

similar_cases = []
for _, row in similar_df.iterrows():
    similar_cases.append({
        "N": int(row['N']),
        "P": int(row['P']),
        "K": int(row['K']),
        "temp": round(float(row['temperature']), 1),
        "humidity": round(float(row['humidity']), 1),
        "ph": round(float(row['ph']), 2),
        "rainfall": round(float(row['rainfall']), 1),
        "label": row['label'].lower()
    })

# Step 6: Final JSON Output
ml_output = {
    "predicted_crop": pred_crop,
    "confidence": confidence,
    "top_3_alternatives": top3_crops,
    "feature_importance": feature_importance,
    "similar_cases": similar_cases,
    "out_of_distribution": not is_valid,
    "validation_warnings": warning_msg if warning_msg else None
}
ml_output = convert_to_serializable(ml_output)
print("✅ ML Layer Output Generated Successfully!\n")
print(json.dumps(ml_output, indent=2))

