# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A92lIB2YR3VgqHXTYSCG4-0kgbC0y-UA
"""

# ==========================================
# STEP 1: INSTALL LIBRARIES
# ==========================================
!pip install -q groq gradio requests

import requests
import gradio as gr
from groq import Groq
import time
import threading
from datetime import datetime, timedelta

import os
# ==========================================
# STEP 2: CONFIGURATION & INTELLIGENCE DATABASES
# ==========================================
OPENWEATHER_API_KEY = os.environ.get("OPENWEATHER_API_KEY", "")
GROQ_API_KEY = os.environ.get("GROQ_API_KEY", "")

PAK_CROPS = ["Wheat", "Cotton", "Rice", "Sugarcane", "Maize", "Mango", "Citrus (Kinnow)", "Potato"]

# CLIMATE & EXTREME WEATHER THRESHOLDS
PAK_CLIMATE_DATA = {
    "Karachi": {"monsoon_start": (7, 5), "flood_threshold_mm": 40, "heatwave_c": 40},
    "Hyderabad": {"monsoon_start": (7, 5), "flood_threshold_mm": 50, "heatwave_c": 42},
    "Multan": {"monsoon_start": (7, 10), "flood_threshold_mm": 80, "heatwave_c": 45},
    "Lahore": {"monsoon_start": (7, 15), "flood_threshold_mm": 0.001, "heatwave_c": 43},
    "Faisalabad": {"monsoon_start": (7, 15), "flood_threshold_mm": 90, "heatwave_c": 10},
    "Peshawar": {"monsoon_start": (7, 20), "flood_threshold_mm": 70, "heatwave_c": 41},
    "Islamabad": {"monsoon_start": (7, 1), "flood_threshold_mm": 120, "heatwave_c": 40},
}
DEFAULT_CLIMATE = {"monsoon_start": (7, 15), "flood_threshold_mm": 80, "heatwave_c": 42}

# GLOBAL STATE FOR AUTOMATION
TARGET_CITY = "Multan"
TARGET_CROP = "Cotton"

automated_messages_db = [
    f"⏳ *System initialized. The Advanced Early Warning System is monitoring **{TARGET_CROP}** in **{TARGET_CITY}**.*"
]

# ==========================================
# STEP 3: THE ADVANCED EARLY WARNING ENGINE
# ==========================================
def check_extreme_risks(city, total_rain_mm, max_temp_c):
    climate = PAK_CLIMATE_DATA.get(city, DEFAULT_CLIMATE)
    alerts = []

    if total_rain_mm >= climate["flood_threshold_mm"]:
        alerts.append(f"🌊 SEVERE FLOOD/WATERLOGGING RISK: {total_rain_mm}mm of rain expected over 5 days.")

    if max_temp_c >= climate["heatwave_c"]:
        alerts.append(f"🔥 HEATWAVE ALERT: Temperatures reaching {max_temp_c}°C. High risk of crop burning and rapid evaporation.")

    today = datetime.now()
    monsoon_date = datetime(today.year, climate["monsoon_start"][0], climate["monsoon_start"][1])
    if today > monsoon_date + timedelta(days=30):
        monsoon_date = datetime(today.year + 1, climate["monsoon_start"][0], climate["monsoon_start"][1])

    days_to_monsoon = (monsoon_date - today).days
    if 0 <= days_to_monsoon <= 5:
        alerts.append(f"⛈️ MONSOON WARNING: Monsoon season begins in {days_to_monsoon} days.")

    return alerts

def fetch_weather_data(city):
    base_url = "http://api.openweathermap.org/data/2.5/forecast"
    params = {"q": city, "appid": OPENWEATHER_API_KEY, "units": "metric"}
    response = requests.get(base_url, params=params)

    if response.status_code != 200:
        return None, None, [], f"Error: Could not retrieve data for '{city}'."

    data = response.json()

    t_data = data['list'][8]
    t_desc = t_data['weather'][0]['description'].title()
    t_temp = t_data['main']['temp']
    tomorrow_summary = f"{t_desc}, Temp: {t_temp}°C"

    weekly_temps = []
    weekly_conds = set()
    total_rain_mm = 0.0
    max_weekly_temp = 0.0

    for item in data['list']:
        temp = item['main']['temp']
        weekly_temps.append(temp)
        weekly_conds.add(item['weather'][0]['description'].title())

        if temp > max_weekly_temp:
            max_weekly_temp = temp

        if 'rain' in item and '3h' in item['rain']:
            total_rain_mm += item['rain']['3h']

    avg_temp = round(sum(weekly_temps) / len(weekly_temps), 1)
    conditions = ", ".join(list(weekly_conds)[:3])
    weekly_summary = f"Avg Temp: {avg_temp}°C, Max Temp: {round(max_weekly_temp, 1)}°C, Total Rain: {round(total_rain_mm, 1)}mm"

    risk_alerts = check_extreme_risks(city, total_rain_mm, max_weekly_temp)

    return tomorrow_summary, weekly_summary, risk_alerts, None

def get_ai_farming_advice(city, crop, context_type="manual"):
    if GROQ_API_KEY == "PASTE_YOUR_GROQ_KEY_HERE":
        return "❌ ERROR: Groq API Key missing."

    tomorrow_forecast, weekly_forecast, risk_alerts, error = fetch_weather_data(city)
    if error: return error

    try:
        client = Groq(api_key=GROQ_API_KEY)
    except Exception as e:
        return f"❌ Groq API Error: {e}"

    warning_injection = ""
    alert_header = ""
    if risk_alerts:
        alert_text = " | ".join(risk_alerts)
        alert_header = f"\n### 🚨 CRITICAL EARLY WARNING\n**{alert_text}**\n"
        warning_injection = f"""
        CRITICAL EMERGENCY INSTRUCTION: Address the active disaster alerts: {alert_text}.
        You MUST provide IN-DEPTH preventive measures.
        If FLOOD/RAIN is detected: Suggest specific fungicides and Gypsum application.
        If HEATWAVE is detected: Suggest specific stress-relief foliar sprays and irrigation scheduling.
        """

    prompt = f"""
    You are AgroBot, an elite agricultural scientist in Pakistan.
    Target City: {city} | Target Crop: {crop}
    Tomorrow's Weather: {tomorrow_forecast}
    5-Day Weekly Trend: {weekly_forecast}

    {warning_injection}

    CRITICAL TRANSLATION AND RENDERING LAWS (MUST FOLLOW):
    1. ZERO HINDI: You are strictly forbidden from using any Devanagari (Hindi) characters. Use strictly Perso-Arabic Urdu script.
    2. ZERO ENGLISH IN URDU SECTION: You must transliterate all English words, chemical names, and numbers into the Urdu script (e.g., write "Gypsum" as "جپسم", "NPK" as "این پی کے", "20%" as "۲۰٪").
    3. HTML WRAPPER: You MUST output the Urdu section inside the provided HTML <div> tag to ensure the web browser renders the sentences properly without breaking.

    Format EXACTLY like this:
    ### 🌾 {crop} Deep Advisory for {city}
    **Tomorrow:** {tomorrow_forecast}
    **Weekly Trend:** {weekly_forecast}
    {alert_header}

    ### 🚜 Immediate Farm Operations
    [2-3 specific English bullet points of physical farm actions for {crop}]

    ### 🧪 Chemical & Disease Management
    [3 detailed English bullet points regarding specific fertilizers, pesticides, or salinity management]

    ### 🇵🇰 تفصیلی زرعی ہدایات
    <div dir="rtl" style="text-align: right; font-family: 'Jameel Noori Nastaleeq', 'Noto Nastaliq Urdu', Arial, sans-serif; font-size: 1.1em; line-height: 1.8;">
    [Translate the above advice into 4 perfect, purely right-to-left Urdu bullet points using strict transliteration. Ensure the Urdu sentence structure flows naturally.]
    </div>
    """

    try:
        chat_completion = client.chat.completions.create(
            messages=[
                {"role": "system", "content": "You are a strict agricultural scientist. Provide deep, chemical-specific farming advice with flawless, unmixed Urdu translations wrapped in HTML."},
                {"role": "user", "content": prompt}
            ],
            model="llama-3.3-70b-versatile",
            temperature=0.1, # Maximize logical consistency
            top_p=0.9 # Prevents the AI from selecting rare "Hindi" tokens
        )
        return chat_completion.choices[0].message.content
    except Exception as e:
        return f"❌ AI Generation Error: {e}"

# ==========================================
# STEP 4: TRUE BACKGROUND AUTOMATION
# ==========================================
def automated_12_hour_loop():
    global TARGET_CITY, TARGET_CROP
    wait_time_seconds = 43200

    while True:
        time.sleep(wait_time_seconds)
        timestamp = datetime.now().strftime("%Y-%m-%d %I:%M %p")
        advice = get_ai_farming_advice(TARGET_CITY, TARGET_CROP, context_type="automated")
        new_alert = f"🔔 **AUTOMATED 12-HOUR UPDATE ({timestamp})**\n\n{advice}"
        automated_messages_db.insert(0, new_alert)
        if len(automated_messages_db) > 10:
            automated_messages_db.pop()

threading.Thread(target=automated_12_hour_loop, daemon=True).start()

def read_automated_messages():
    return "\n\n---\n\n".join(automated_messages_db)

def update_preferences(new_city, new_crop):
    global TARGET_CITY, TARGET_CROP
    TARGET_CITY = new_city.strip()
    TARGET_CROP = new_crop
    timestamp = datetime.now().strftime("%I:%M %p")
    system_msg = f"⚙️ *System Update ({timestamp}): Early Warning System now tracking **{TARGET_CROP}** in **{TARGET_CITY}**.*"
    automated_messages_db.insert(0, system_msg)
    return f"✅ Success! Background engine updated."

# ==========================================
# STEP 5: THE APP INTERFACE
# ==========================================
custom_theme = gr.themes.Soft(primary_hue="red", secondary_hue="orange")

with gr.Blocks(theme=custom_theme) as app:
    gr.Markdown("# 🚨 AgroBot Early Warning & Precision Ag Platform")
    gr.Markdown("Deep-analysis agronomic module featuring Heatwave tracking, Flood detection, Salinity management, and Specific Chemical Interventions.")

    with gr.Tabs():
        with gr.Tab("📱 Automated Alerts (12-Hour)"):
            message_board = gr.Markdown(value=read_automated_messages())
            auto_timer = gr.Timer(30)
            auto_timer.tick(fn=read_automated_messages, inputs=None, outputs=message_board)

        with gr.Tab("🔍 Manual Live Check"):
            with gr.Row():
                manual_city = gr.Textbox(label="City", placeholder="e.g., Lahore", scale=1)
                manual_crop = gr.Dropdown(choices=PAK_CROPS, label="Select Crop", value="Mango", scale=1)
                check_btn = gr.Button("Run Deep Disaster & Disease Analysis", variant="primary", scale=1)
            manual_output = gr.Markdown()
            check_btn.click(fn=get_ai_farming_advice, inputs=[manual_city, manual_crop], outputs=manual_output)

        with gr.Tab("⚙️ Setup Automation"):
            with gr.Row():
                pref_city = gr.Textbox(label="Farm City", value=TARGET_CITY, scale=1)
                pref_crop = gr.Dropdown(choices=PAK_CROPS, label="Primary Crop", value=TARGET_CROP, scale=1)
                save_pref_btn = gr.Button("Update Background AI", variant="secondary", scale=1)
            pref_status = gr.Markdown()
            save_pref_btn.click(fn=update_preferences, inputs=[pref_city, pref_crop], outputs=pref_status)

app.launch(share=True, debug=True)